// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuizcraftBank struct {
	ID               uuid.UUID          `json:"id"`
	BankKey          string             `json:"bank_key"`
	Name             string             `json:"name"`
	ActiveVersionID  uuid.NullUUID      `json:"active_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LifecycleVersion int64              `json:"lifecycle_version"`
}

type QuizcraftBankVersion struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	Name          string             `json:"name"`
	SourceVersion string             `json:"source_version"`
	SourceSha256  string             `json:"source_sha256"`
	ContentSha256 string             `json:"content_sha256"`
	ImportReport  []byte             `json:"import_report"`
	ImportedAt    pgtype.Timestamptz `json:"imported_at"`
	SealedAt      pgtype.Timestamptz `json:"sealed_at"`
}

type QuizcraftBankVersionQuestion struct {
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

type QuizcraftFavorite struct {
	UserID     uuid.UUID          `json:"user_id"`
	BankID     uuid.UUID          `json:"bank_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftFeedback struct {
	ID                   uuid.UUID          `json:"id"`
	BankID               uuid.UUID          `json:"bank_id"`
	QuestionID           uuid.UUID          `json:"question_id"`
	QuestionVersionID    uuid.UUID          `json:"question_version_id"`
	ActorUserID          uuid.NullUUID      `json:"actor_user_id"`
	ActorKey             string             `json:"actor_key"`
	Category             string             `json:"category"`
	Detail               string             `json:"detail"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	LegacyFeedbackID     pgtype.Text        `json:"legacy_feedback_id"`
	LegacyStatus         string             `json:"legacy_status"`
	LegacyResolvedAt     pgtype.Timestamptz `json:"legacy_resolved_at"`
	LegacyResolutionNote string             `json:"legacy_resolution_note"`
}

type QuizcraftFeedbackInboxDelivery struct {
	OutboxID       uuid.UUID          `json:"outbox_id"`
	PlatformItemID uuid.NullUUID      `json:"platform_item_id"`
	Attempts       int32              `json:"attempts"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	LastError      string             `json:"last_error"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
}

type QuizcraftFeedbackInboxOutbox struct {
	ID                 uuid.UUID          `json:"id"`
	FeedbackID         uuid.UUID          `json:"feedback_id"`
	SourceProductCode  string             `json:"source_product_code"`
	SourceResourceType string             `json:"source_resource_type"`
	SourceResourceID   string             `json:"source_resource_id"`
	SourceResourceUrl  string             `json:"source_resource_url"`
	Category           string             `json:"category"`
	Priority           string             `json:"priority"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftFeedbackStatusFact struct {
	ID            uuid.UUID          `json:"id"`
	FeedbackID    uuid.UUID          `json:"feedback_id"`
	Status        string             `json:"status"`
	Source        string             `json:"source"`
	SourceEventID string             `json:"source_event_id"`
	SourceVersion pgtype.Int8        `json:"source_version"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt    pgtype.Timestamptz `json:"recorded_at"`
}

type QuizcraftIdempotencyResult struct {
	ActorKey       string             `json:"actor_key"`
	OperationKind  string             `json:"operation_kind"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestSha256  string             `json:"request_sha256"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   string             `json:"response_body"`
	ResourceID     uuid.NullUUID      `json:"resource_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftLearningCatalog struct {
	BankID                 uuid.UUID          `json:"bank_id"`
	ActiveContentVersionID uuid.NullUUID      `json:"active_content_version_id"`
	Enabled                bool               `json:"enabled"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftLearningContentReview struct {
	ID               uuid.UUID          `json:"id"`
	BankID           uuid.UUID          `json:"bank_id"`
	ContentVersionID uuid.UUID          `json:"content_version_id"`
	ActorUserID      uuid.UUID          `json:"actor_user_id"`
	Action           string             `json:"action"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftLearningContentVersion struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	BankVersionID uuid.UUID          `json:"bank_version_id"`
	ContentSha256 string             `json:"content_sha256"`
	Document      []byte             `json:"document"`
	Status        string             `json:"status"`
	ReviewedBy    uuid.NullUUID      `json:"reviewed_by"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftLearningReport struct {
	ID               uuid.UUID          `json:"id"`
	JobID            uuid.UUID          `json:"job_id"`
	UserID           uuid.UUID          `json:"user_id"`
	BankID           uuid.UUID          `json:"bank_id"`
	ContentVersionID uuid.UUID          `json:"content_version_id"`
	LeaseToken       uuid.UUID          `json:"lease_token"`
	EvidenceUntil    pgtype.Timestamptz `json:"evidence_until"`
	Status           string             `json:"status"`
	Body             []byte             `json:"body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftLearningReportJob struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	BankID             uuid.UUID          `json:"bank_id"`
	PreferenceRevision int64              `json:"preference_revision"`
	ContentVersionID   uuid.UUID          `json:"content_version_id"`
	InputSha256        string             `json:"input_sha256"`
	Snapshot           []byte             `json:"snapshot"`
	Status             string             `json:"status"`
	RunAfter           pgtype.Timestamptz `json:"run_after"`
	Attempts           int32              `json:"attempts"`
	LeaseToken         uuid.NullUUID      `json:"lease_token"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	ReasonCode         string             `json:"reason_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftLearningReportPreference struct {
	UserID                  uuid.UUID          `json:"user_id"`
	BankID                  uuid.UUID          `json:"bank_id"`
	Enabled                 bool               `json:"enabled"`
	IntervalDays            int32              `json:"interval_days"`
	Goal                    string             `json:"goal"`
	ChapterIds              []byte             `json:"chapter_ids"`
	ExternalAnalysisConsent bool               `json:"external_analysis_consent"`
	ConsentVersion          string             `json:"consent_version"`
	Revision                int64              `json:"revision"`
	NextDueAt               pgtype.Timestamptz `json:"next_due_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftLearningState struct {
	UserID            uuid.UUID          `json:"user_id"`
	BankID            uuid.UUID          `json:"bank_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	Wrong             bool               `json:"wrong"`
	AttemptCount      int64              `json:"attempt_count"`
	CorrectCount      int64              `json:"correct_count"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LatestAttemptID   uuid.UUID          `json:"latest_attempt_id"`
}

type QuizcraftLegacyFeedbackArchive struct {
	ID               uuid.UUID          `json:"id"`
	SourceName       string             `json:"source_name"`
	LegacyFeedbackID string             `json:"legacy_feedback_id"`
	BankKey          string             `json:"bank_key"`
	SourceQuestionID string             `json:"source_question_id"`
	QuestionIndex    int32              `json:"question_index"`
	QuestionContent  string             `json:"question_content"`
	LegacyUserID     string             `json:"legacy_user_id"`
	SourcePage       string             `json:"source_page"`
	Detail           string             `json:"detail"`
	LegacyStatus     string             `json:"legacy_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ResolutionNote   string             `json:"resolution_note"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
}

type QuizcraftLegacyFeedbackStateEvent struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	LegacyFeedbackID string             `json:"legacy_feedback_id"`
	SourceEventID    int64              `json:"source_event_id"`
	Status           string             `json:"status"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ResolutionNote   string             `json:"resolution_note"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
}

type QuizcraftLegacyRankingSnapshot struct {
	ID            uuid.UUID          `json:"id"`
	RunID         uuid.UUID          `json:"run_id"`
	SourceEventID int64              `json:"source_event_id"`
	Standings     []byte             `json:"standings"`
	ContentSha256 string             `json:"content_sha256"`
	CapturedAt    pgtype.Timestamptz `json:"captured_at"`
}

type QuizcraftMigrationEventReceipt struct {
	SourceName    string             `json:"source_name"`
	SourceEventID int64              `json:"source_event_id"`
	RunID         uuid.UUID          `json:"run_id"`
	EventType     string             `json:"event_type"`
	AggregateKey  string             `json:"aggregate_key"`
	PayloadSha256 string             `json:"payload_sha256"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
}

type QuizcraftMigrationException struct {
	ID             uuid.UUID          `json:"id"`
	RunID          uuid.UUID          `json:"run_id"`
	RecordType     string             `json:"record_type"`
	LegacyRecordID string             `json:"legacy_record_id"`
	ReasonCode     string             `json:"reason_code"`
	Detail         []byte             `json:"detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftMigrationExceptionResolution struct {
	ID                uuid.UUID          `json:"id"`
	ExceptionID       uuid.UUID          `json:"exception_id"`
	ResolvedByEventID int64              `json:"resolved_by_event_id"`
	Resolution        string             `json:"resolution"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftMigrationRun struct {
	ID                   uuid.UUID          `json:"id"`
	SourceName           string             `json:"source_name"`
	SourceCutoffEventID  int64              `json:"source_cutoff_event_id"`
	CaughtUpEventID      int64              `json:"caught_up_event_id"`
	State                string             `json:"state"`
	Report               []byte             `json:"report"`
	ReportSha256         string             `json:"report_sha256"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	SourceSnapshotSha256 string             `json:"source_snapshot_sha256"`
	ResumeAttemptCount   int32              `json:"resume_attempt_count"`
}

type QuizcraftPracticeAttempt struct {
	ID                uuid.UUID          `json:"id"`
	SessionID         uuid.UUID          `json:"session_id"`
	BankID            uuid.UUID          `json:"bank_id"`
	BankVersionID     uuid.UUID          `json:"bank_version_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	QuestionVersionID uuid.UUID          `json:"question_version_id"`
	UserID            uuid.NullUUID      `json:"user_id"`
	SubmittedAnswer   []byte             `json:"submitted_answer"`
	Correct           bool               `json:"correct"`
	ExpectedAnswer    []byte             `json:"expected_answer"`
	Analysis          string             `json:"analysis"`
	ResponseBody      string             `json:"response_body"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
}

type QuizcraftPracticeSession struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	BankVersionID uuid.UUID          `json:"bank_version_id"`
	UserID        uuid.NullUUID      `json:"user_id"`
	ActorKey      string             `json:"actor_key"`
	Mode          string             `json:"mode"`
	ChapterID     pgtype.Text        `json:"chapter_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftPracticeSessionClaim struct {
	SessionID     uuid.UUID          `json:"session_id"`
	GuestActorKey string             `json:"guest_actor_key"`
	UserID        uuid.UUID          `json:"user_id"`
	UserActorKey  string             `json:"user_actor_key"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
}

type QuizcraftPracticeSessionQuestion struct {
	SessionID         uuid.UUID `json:"session_id"`
	BankID            uuid.UUID `json:"bank_id"`
	BankVersionID     uuid.UUID `json:"bank_version_id"`
	QuestionID        uuid.UUID `json:"question_id"`
	QuestionVersionID uuid.UUID `json:"question_version_id"`
	Position          int32     `json:"position"`
}

type QuizcraftQuestion struct {
	ID               uuid.UUID          `json:"id"`
	BankID           uuid.UUID          `json:"bank_id"`
	SourceQuestionID string             `json:"source_question_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftQuestionStat struct {
	QuestionID   uuid.UUID          `json:"question_id"`
	AttemptCount int64              `json:"attempt_count"`
	CorrectCount int64              `json:"correct_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftQuestionVersion struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	QuestionID    uuid.UUID          `json:"question_id"`
	Type          string             `json:"type"`
	ChapterID     string             `json:"chapter_id"`
	ChapterName   string             `json:"chapter_name"`
	Content       string             `json:"content"`
	Options       []byte             `json:"options"`
	Answer        []byte             `json:"answer"`
	Analysis      string             `json:"analysis"`
	ContentSha256 string             `json:"content_sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftRankingProfile struct {
	UserID       uuid.UUID          `json:"user_id"`
	Nickname     string             `json:"nickname"`
	SystemAvatar string             `json:"system_avatar"`
	Visible      bool               `json:"visible"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizcraftRankingSettlementEvent struct {
	ID          uuid.UUID          `json:"id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	Scope       string             `json:"scope"`
	BankID      uuid.NullUUID      `json:"bank_id"`
	Metric      string             `json:"metric"`
	Standings   []byte             `json:"standings"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftServiceNonce struct {
	ClientID   string             `json:"client_id"`
	KeyID      string             `json:"key_id"`
	Nonce      string             `json:"nonce"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type QuizcraftShadowComparison struct {
	ID             uuid.UUID          `json:"id"`
	SessionID      uuid.UUID          `json:"session_id"`
	QuestionID     uuid.UUID          `json:"question_id"`
	NewResponse    []byte             `json:"new_response"`
	LegacyResponse []byte             `json:"legacy_response"`
	Outcome        string             `json:"outcome"`
	Detail         string             `json:"detail"`
	ComparedAt     pgtype.Timestamptz `json:"compared_at"`
}

type QuizcraftShadowGateReport struct {
	ID                 uuid.UUID          `json:"id"`
	WindowStart        pgtype.Timestamptz `json:"window_start"`
	WindowEnd          pgtype.Timestamptz `json:"window_end"`
	SampleCount        int64              `json:"sample_count"`
	MismatchCount      int64              `json:"mismatch_count"`
	LegacyErrorCount   int64              `json:"legacy_error_count"`
	MismatchRate       float64            `json:"mismatch_rate"`
	MismatchThreshold  float64            `json:"mismatch_threshold"`
	MinimumSampleCount int64              `json:"minimum_sample_count"`
	Decision           string             `json:"decision"`
	Reasons            []byte             `json:"reasons"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftWorkshopAuditEvent struct {
	ID               uuid.UUID          `json:"id"`
	ActorUserID      uuid.UUID          `json:"actor_user_id"`
	PermissionCode   string             `json:"permission_code"`
	Action           string             `json:"action"`
	BankID           uuid.UUID          `json:"bank_id"`
	BankVersionID    uuid.NullUUID      `json:"bank_version_id"`
	ExpectedVersion  int64              `json:"expected_version"`
	ResultingVersion int64              `json:"resulting_version"`
	RequestID        string             `json:"request_id"`
	Note             string             `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type QuizcraftWorkshopVersionState struct {
	BankID         uuid.UUID          `json:"bank_id"`
	BankVersionID  uuid.UUID          `json:"bank_version_id"`
	State          string             `json:"state"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	ValidatedBy    uuid.NullUUID      `json:"validated_by"`
	ValidationNote string             `json:"validation_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ValidatedAt    pgtype.Timestamptz `json:"validated_at"`
}
