// Code generated by cmd/quizcraftcontractgen from quizcraft.yaml; DO NOT EDIT.
package practice

const QuizCraftCatalogContractSHA256 = "6a5b4ecd6a5fe3c15f3b5637ff14dba5fc3996a1e036ad7e376432e4cb881dfa"
const QuizCraftRankingContractSHA256 = QuizCraftCatalogContractSHA256
const ListPracticeBanksPath = "/api/v1/banks"
const GetPersonalPracticeStatsPath = "/api/v1/stats"
const OverallRankingPath = "/api/v1/rankings/overall"
const BankRankingPath = "/api/v1/banks/{bank_id}/rankings"
const CreatePortalPracticeSessionPath = "/api/v1/portal/practice/sessions"
const SubmitPortalPracticeAnswerPath = "/api/v1/portal/practice/sessions/{session_id}/answers"
const CreatePortalPracticeFeedbackPath = "/api/v1/portal/practice/feedback"
const GetPortalPracticeFeedbackStatusPath = "/api/v1/portal/practice/feedback/{feedback_id}/status"
const GetPortalFavoritesOverviewPath = "/api/v1/portal/practice/favorites"
const ListPortalFavoriteQuestionsPath = "/api/v1/portal/practice/banks/{bank_id}/favorites"
const FavoritePortalQuestionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/{question_id}"
const UnfavoritePortalQuestionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/{question_id}"
const CreatePortalFavoritesSessionPath = "/api/v1/portal/practice/banks/{bank_id}/favorites/practice-sessions"
const GetPortalLearningReportPreferencesPath = "/api/v1/portal/practice/banks/{bank_id}/learning-reports/preferences"
const GetPortalLatestLearningReportPath = "/api/v1/portal/practice/banks/{bank_id}/learning-reports/latest"
const GetPortalLearningReportTaskPath = "/api/v1/portal/practice/banks/{bank_id}/learning-reports/tasks/{task_id}"

// BankListEnvelope is the generated read-only QuizCraft catalog response.
// Its data members are the published, and therefore available, bank versions.
type BankListEnvelope struct {
	RequestID string        `json:"request_id"`
	Data      []BankVersion `json:"data"`
}

// BankVersion is the stable published version of one QuizCraft bank.
type BankVersion struct {
	BankID        string    `json:"bank_id"`
	BankVersionID string    `json:"bank_version_id"`
	BankKey       string    `json:"bank_key"`
	Name          string    `json:"name"`
	ContentSHA256 string    `json:"content_sha256"`
	QuestionCount int       `json:"question_count"`
	Chapters      []Chapter `json:"chapters"`
}

// Chapter is a published QuizCraft bank chapter.
type Chapter struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RankingPeriod string

const (
	RankingPeriodWeekly   RankingPeriod = "weekly"
	RankingPeriodLifetime RankingPeriod = "lifetime"
)

// RankingEnvelope is the generated internal Portal read contract. Entries
// carry a nullable user_id plus a nullable guest_key (the stable anonymous
// identity for guest learners) that the Portal Gateway MUST strip before any
// external response and MUST NOT render as a nickname (ADR-0038; ADR-0036
// privacy contract unchanged).
type RankingEnvelope struct {
	RequestID string      `json:"request_id"`
	Data      RankingPage `json:"data"`
}

type RankingPage struct {
	Scope   string         `json:"scope"`
	BankID  string         `json:"bank_id,omitempty"`
	Period  RankingPeriod  `json:"period"`
	Metric  string         `json:"metric"`
	Entries []RankingEntry `json:"entries"`
}

type RankingEntry struct {
	Rank               int64   `json:"rank"`
	UserID             *string `json:"user_id"`
	GuestKey           *string `json:"guest_key"`
	CorrectAnswerCount int64   `json:"correct_answer_count"`
}

// PersonalPracticeStatsEnvelope is one authenticated Portal user's
// fact-derived QuizCraft statistics. It never represents a mock response.
type PersonalPracticeStatsEnvelope struct {
	RequestID string                `json:"request_id"`
	Data      PersonalPracticeStats `json:"data"`
}

type PersonalPracticeStats struct {
	TotalAnswers   int64            `json:"total_answers"`
	CorrectAnswers int64            `json:"correct_answers"`
	Accuracy       int              `json:"accuracy"`
	StreakDays     int              `json:"streak_days"`
	Mastery        []MasterySubject `json:"mastery"`
}

type MasterySubject struct {
	BankID           string `json:"bank_id"`
	Label            string `json:"label"`
	Value            int    `json:"value"`
	TotalQuestions   int64  `json:"total_questions"`
	CorrectQuestions int64  `json:"correct_questions"`
}

// FeedbackStatusEnvelope is one authenticated Portal user's persisted
// correction processing status. It never represents a mock response.
type FeedbackStatusEnvelope struct {
	RequestID string         `json:"request_id"`
	Data      FeedbackStatus `json:"data"`
}

type FeedbackStatus struct {
	FeedbackID        string `json:"feedback_id"`
	BankID            string `json:"bank_id"`
	QuestionID        string `json:"question_id"`
	QuestionVersionID string `json:"question_version_id"`
	Category          string `json:"category"`
	Status            string `json:"status"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

// FavoritesOverviewEnvelope lists one signed-in Portal user's automatic
// per-bank favorite folders. It never represents a mock response.
type FavoritesOverviewEnvelope struct {
	RequestID string           `json:"request_id"`
	Data      []FavoriteFolder `json:"data"`
}

type FavoriteFolder struct {
	BankID           string `json:"bank_id"`
	BankName         string `json:"bank_name"`
	AvailableCount   int    `json:"available_count"`
	UnavailableCount int    `json:"unavailable_count"`
}

// FavoriteListEnvelope lists one bank's favorite references for one user.
// Unavailable items expose references only; available items carry the content
// version id.
type FavoriteListEnvelope struct {
	RequestID string             `json:"request_id"`
	Data      []FavoriteQuestion `json:"data"`
}

type FavoriteQuestion struct {
	BankID            string `json:"bank_id"`
	QuestionID        string `json:"question_id"`
	Available         bool   `json:"available"`
	QuestionVersionID string `json:"question_version_id,omitempty"`
}

// LearningReportPreferencesEnvelope is one signed-in Portal user's
// course-scoped feedback preferences. Missing preferences are reported by the
// Core as disabled seven-day defaults, never as a mock.
type LearningReportPreferencesEnvelope struct {
	RequestID string                    `json:"request_id"`
	Data      LearningReportPreferences `json:"data"`
}

type LearningReportPreferences struct {
	Enabled                 bool     `json:"enabled"`
	IntervalDays            int      `json:"interval_days"`
	Goal                    string   `json:"goal"`
	ChapterIDs              []string `json:"chapter_ids"`
	ExternalAnalysisConsent bool     `json:"external_analysis_consent"`
	BankID                  string   `json:"bank_id"`
	Revision                int64    `json:"revision"`
	NextDueAt               *string  `json:"next_due_at,omitempty"`
	UpdatedAt               *string  `json:"updated_at,omitempty"`
}

// LearningReportTaskEnvelope is one queued or finished course-report task.
// The Gateway mirrors only the Portal-visible progress fields.
type LearningReportTaskEnvelope struct {
	RequestID string             `json:"request_id"`
	Data      LearningReportTask `json:"data"`
}

type LearningReportTask struct {
	TaskID            string  `json:"task_id"`
	BankID            string  `json:"bank_id"`
	Status            string  `json:"status"`
	CreatedAt         string  `json:"created_at"`
	ReportID          *string `json:"report_id,omitempty"`
	ReasonCode        *string `json:"reason_code,omitempty"`
	RetryAfterSeconds *int    `json:"retry_after_seconds,omitempty"`
}

// LearningReportEnvelope is one published course report. It carries the
// server-derived statistics, the owner's own answer evidence and the model's
// explicitly hypothetical observations; the Gateway re-serializes only these
// mirrored members, so no unmodelled Core field can reach a browser.
type LearningReportEnvelope struct {
	RequestID string         `json:"request_id"`
	Data      LearningReport `json:"data"`
}

type LearningReport struct {
	ReportID         string                    `json:"report_id"`
	BankID           string                    `json:"bank_id"`
	ContentVersionID string                    `json:"content_version_id"`
	Status           string                    `json:"status"`
	Goal             string                    `json:"goal"`
	EvidenceUntil    string                    `json:"evidence_until"`
	CreatedAt        string                    `json:"created_at"`
	Statistics       []LearningReportStatistic `json:"statistics"`
	Evidence         []LearningReportEvidence  `json:"evidence"`
	Findings         []LearningReportFinding   `json:"findings"`
	NextStep         LearningReportAction      `json:"next_step"`
}

type LearningReportStatistic struct {
	TagID               string `json:"tag_id"`
	TagKind             string `json:"tag_kind"`
	Label               string `json:"label"`
	AttemptCount        int64  `json:"attempt_count"`
	UniqueQuestionCount int64  `json:"unique_question_count"`
	FirstCorrectCount   int64  `json:"first_correct_count"`
	RepeatAttemptCount  int64  `json:"repeat_attempt_count"`
	RepeatCorrectCount  int64  `json:"repeat_correct_count"`
	LatestCorrectCount  int64  `json:"latest_correct_count"`
}

type LearningReportEvidence struct {
	EvidenceID        string `json:"evidence_id"`
	QuestionID        string `json:"question_id"`
	QuestionVersionID string `json:"question_version_id"`
	SubmittedAt       string `json:"submitted_at"`
	Correct           bool   `json:"correct"`
	Question          string `json:"question"`
	SubmittedAnswer   any    `json:"submitted_answer"`
	ExpectedAnswer    any    `json:"expected_answer"`
}

type LearningReportFinding struct {
	TagID          string   `json:"tag_id"`
	Status         string   `json:"status"`
	Observation    string   `json:"observation"`
	PossibleReason *string  `json:"possible_reason,omitempty"`
	EvidenceIDs    []string `json:"evidence_ids"`
}

type LearningReportAction struct {
	Kind        string                `json:"kind"`
	Reason      string                `json:"reason"`
	TagID       *string               `json:"tag_id,omitempty"`
	Lesson      *LearningReportLesson `json:"lesson,omitempty"`
	QuestionIDs []string              `json:"question_ids,omitempty"`
}

type LearningReportLesson struct {
	LessonID string                 `json:"lesson_id"`
	Title    string                 `json:"title"`
	Body     string                 `json:"body"`
	Sources  []LearningReportSource `json:"sources"`
}

type LearningReportSource struct {
	SourceID string `json:"source_id"`
	Title    string `json:"title"`
	Version  string `json:"version"`
	Locator  string `json:"locator"`
}
