// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChapterPracticeSelectionMode.
const (
	ChapterPracticeSelectionModeChapter ChapterPracticeSelectionMode = "chapter"
)

// Valid indicates whether the value is a known member of the ChapterPracticeSelectionMode enum.
func (e ChapterPracticeSelectionMode) Valid() bool {
	switch e {
	case ChapterPracticeSelectionModeChapter:
		return true
	default:
		return false
	}
}

// Defines values for ChoicePracticeQuestionType.
const (
	ChoicePracticeQuestionTypeMulti  ChoicePracticeQuestionType = "multi"
	ChoicePracticeQuestionTypeSingle ChoicePracticeQuestionType = "single"
)

// Valid indicates whether the value is a known member of the ChoicePracticeQuestionType enum.
func (e ChoicePracticeQuestionType) Valid() bool {
	switch e {
	case ChoicePracticeQuestionTypeMulti:
		return true
	case ChoicePracticeQuestionTypeSingle:
		return true
	default:
		return false
	}
}

// Defines values for ConsoleSummaryEnvelopeDataId.
const (
	Quizcraft ConsoleSummaryEnvelopeDataId = "quizcraft"
)

// Valid indicates whether the value is a known member of the ConsoleSummaryEnvelopeDataId enum.
func (e ConsoleSummaryEnvelopeDataId) Valid() bool {
	switch e {
	case Quizcraft:
		return true
	default:
		return false
	}
}

// Defines values for ConsoleSummaryEnvelopeDataStatus.
const (
	ConsoleSummaryEnvelopeDataStatusEmpty   ConsoleSummaryEnvelopeDataStatus = "empty"
	ConsoleSummaryEnvelopeDataStatusOk      ConsoleSummaryEnvelopeDataStatus = "ok"
	ConsoleSummaryEnvelopeDataStatusPartial ConsoleSummaryEnvelopeDataStatus = "partial"
)

// Valid indicates whether the value is a known member of the ConsoleSummaryEnvelopeDataStatus enum.
func (e ConsoleSummaryEnvelopeDataStatus) Valid() bool {
	switch e {
	case ConsoleSummaryEnvelopeDataStatusEmpty:
		return true
	case ConsoleSummaryEnvelopeDataStatusOk:
		return true
	case ConsoleSummaryEnvelopeDataStatusPartial:
		return true
	default:
		return false
	}
}

// Defines values for CutoverEvidenceEnvelopeDataDatabase.
const (
	CutoverEvidenceEnvelopeDataDatabaseReady CutoverEvidenceEnvelopeDataDatabase = "ready"
)

// Valid indicates whether the value is a known member of the CutoverEvidenceEnvelopeDataDatabase enum.
func (e CutoverEvidenceEnvelopeDataDatabase) Valid() bool {
	switch e {
	case CutoverEvidenceEnvelopeDataDatabaseReady:
		return true
	default:
		return false
	}
}

// Defines values for DifficultPracticeSelectionMode.
const (
	DifficultPracticeSelectionModeDifficult DifficultPracticeSelectionMode = "difficult"
)

// Valid indicates whether the value is a known member of the DifficultPracticeSelectionMode enum.
func (e DifficultPracticeSelectionMode) Valid() bool {
	switch e {
	case DifficultPracticeSelectionModeDifficult:
		return true
	default:
		return false
	}
}

// Defines values for FeedbackStatusCategory.
const (
	FeedbackStatusCategoryAmbiguous   FeedbackStatusCategory = "ambiguous"
	FeedbackStatusCategoryOther       FeedbackStatusCategory = "other"
	FeedbackStatusCategoryOutdated    FeedbackStatusCategory = "outdated"
	FeedbackStatusCategoryTypo        FeedbackStatusCategory = "typo"
	FeedbackStatusCategoryWrongAnswer FeedbackStatusCategory = "wrong_answer"
)

// Valid indicates whether the value is a known member of the FeedbackStatusCategory enum.
func (e FeedbackStatusCategory) Valid() bool {
	switch e {
	case FeedbackStatusCategoryAmbiguous:
		return true
	case FeedbackStatusCategoryOther:
		return true
	case FeedbackStatusCategoryOutdated:
		return true
	case FeedbackStatusCategoryTypo:
		return true
	case FeedbackStatusCategoryWrongAnswer:
		return true
	default:
		return false
	}
}

// Defines values for FeedbackStatusStatus.
const (
	FeedbackStatusStatusArchived   FeedbackStatusStatus = "archived"
	FeedbackStatusStatusBlocked    FeedbackStatusStatus = "blocked"
	FeedbackStatusStatusInProgress FeedbackStatusStatus = "in_progress"
	FeedbackStatusStatusPending    FeedbackStatusStatus = "pending"
	FeedbackStatusStatusResolved   FeedbackStatusStatus = "resolved"
)

// Valid indicates whether the value is a known member of the FeedbackStatusStatus enum.
func (e FeedbackStatusStatus) Valid() bool {
	switch e {
	case FeedbackStatusStatusArchived:
		return true
	case FeedbackStatusStatusBlocked:
		return true
	case FeedbackStatusStatusInProgress:
		return true
	case FeedbackStatusStatusPending:
		return true
	case FeedbackStatusStatusResolved:
		return true
	default:
		return false
	}
}

// Defines values for HealthEnvelopeDataStatus.
const (
	HealthEnvelopeDataStatusOk HealthEnvelopeDataStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthEnvelopeDataStatus enum.
func (e HealthEnvelopeDataStatus) Valid() bool {
	switch e {
	case HealthEnvelopeDataStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportGoal.
const (
	LearningReportGoalExamReview   LearningReportGoal = "exam_review"
	LearningReportGoalFollowCourse LearningReportGoal = "follow_course"
)

// Valid indicates whether the value is a known member of the LearningReportGoal enum.
func (e LearningReportGoal) Valid() bool {
	switch e {
	case LearningReportGoalExamReview:
		return true
	case LearningReportGoalFollowCourse:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportStatus.
const (
	LearningReportStatusInsufficientEvidence LearningReportStatus = "insufficient_evidence"
	LearningReportStatusReady                LearningReportStatus = "ready"
	LearningReportStatusStale                LearningReportStatus = "stale"
)

// Valid indicates whether the value is a known member of the LearningReportStatus enum.
func (e LearningReportStatus) Valid() bool {
	switch e {
	case LearningReportStatusInsufficientEvidence:
		return true
	case LearningReportStatusReady:
		return true
	case LearningReportStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportActionKind.
const (
	ContentUnavailable LearningReportActionKind = "content_unavailable"
	Diagnostic         LearningReportActionKind = "diagnostic"
	NoAction           LearningReportActionKind = "no_action"
	Practice           LearningReportActionKind = "practice"
)

// Valid indicates whether the value is a known member of the LearningReportActionKind enum.
func (e LearningReportActionKind) Valid() bool {
	switch e {
	case ContentUnavailable:
		return true
	case Diagnostic:
		return true
	case NoAction:
		return true
	case Practice:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportFindingStatus.
const (
	Supported LearningReportFindingStatus = "supported"
	Tentative LearningReportFindingStatus = "tentative"
	Uncovered LearningReportFindingStatus = "uncovered"
)

// Valid indicates whether the value is a known member of the LearningReportFindingStatus enum.
func (e LearningReportFindingStatus) Valid() bool {
	switch e {
	case Supported:
		return true
	case Tentative:
		return true
	case Uncovered:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportPreferencesGoal.
const (
	LearningReportPreferencesGoalExamReview   LearningReportPreferencesGoal = "exam_review"
	LearningReportPreferencesGoalFollowCourse LearningReportPreferencesGoal = "follow_course"
)

// Valid indicates whether the value is a known member of the LearningReportPreferencesGoal enum.
func (e LearningReportPreferencesGoal) Valid() bool {
	switch e {
	case LearningReportPreferencesGoalExamReview:
		return true
	case LearningReportPreferencesGoalFollowCourse:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportPreferencesUpdateGoal.
const (
	LearningReportPreferencesUpdateGoalExamReview   LearningReportPreferencesUpdateGoal = "exam_review"
	LearningReportPreferencesUpdateGoalFollowCourse LearningReportPreferencesUpdateGoal = "follow_course"
)

// Valid indicates whether the value is a known member of the LearningReportPreferencesUpdateGoal enum.
func (e LearningReportPreferencesUpdateGoal) Valid() bool {
	switch e {
	case LearningReportPreferencesUpdateGoalExamReview:
		return true
	case LearningReportPreferencesUpdateGoalFollowCourse:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportStatisticTagKind.
const (
	Ability   LearningReportStatisticTagKind = "ability"
	Knowledge LearningReportStatisticTagKind = "knowledge"
)

// Valid indicates whether the value is a known member of the LearningReportStatisticTagKind enum.
func (e LearningReportStatisticTagKind) Valid() bool {
	switch e {
	case Ability:
		return true
	case Knowledge:
		return true
	default:
		return false
	}
}

// Defines values for LearningReportTaskStatus.
const (
	LearningReportTaskStatusCancelled LearningReportTaskStatus = "cancelled"
	LearningReportTaskStatusFailed    LearningReportTaskStatus = "failed"
	LearningReportTaskStatusPaused    LearningReportTaskStatus = "paused"
	LearningReportTaskStatusQueued    LearningReportTaskStatus = "queued"
	LearningReportTaskStatusReady     LearningReportTaskStatus = "ready"
	LearningReportTaskStatusRunning   LearningReportTaskStatus = "running"
)

// Valid indicates whether the value is a known member of the LearningReportTaskStatus enum.
func (e LearningReportTaskStatus) Valid() bool {
	switch e {
	case LearningReportTaskStatusCancelled:
		return true
	case LearningReportTaskStatusFailed:
		return true
	case LearningReportTaskStatusPaused:
		return true
	case LearningReportTaskStatusQueued:
		return true
	case LearningReportTaskStatusReady:
		return true
	case LearningReportTaskStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for NonChoicePracticeQuestionType.
const (
	NonChoicePracticeQuestionTypeBlank NonChoicePracticeQuestionType = "blank"
	NonChoicePracticeQuestionTypeJudge NonChoicePracticeQuestionType = "judge"
)

// Valid indicates whether the value is a known member of the NonChoicePracticeQuestionType enum.
func (e NonChoicePracticeQuestionType) Valid() bool {
	switch e {
	case NonChoicePracticeQuestionTypeBlank:
		return true
	case NonChoicePracticeQuestionTypeJudge:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	OperationStatePending   OperationState = "pending"
	OperationStateRejected  OperationState = "rejected"
	OperationStateSucceeded OperationState = "succeeded"
	OperationStateUnknown   OperationState = "unknown"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case OperationStatePending:
		return true
	case OperationStateRejected:
		return true
	case OperationStateSucceeded:
		return true
	case OperationStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for OperationKind.
const (
	OperationKindCreateBankVersion      OperationKind = "create_bank_version"
	OperationKindCreateFavoritesSession OperationKind = "create_favorites_session"
	OperationKindCreateFeedback         OperationKind = "create_feedback"
	OperationKindCreatePracticeSession  OperationKind = "create_practice_session"
	OperationKindCreateWorkshopBank     OperationKind = "create_workshop_bank"
	OperationKindFavoriteQuestion       OperationKind = "favorite_question"
	OperationKindImportBank             OperationKind = "import_bank"
	OperationKindPublishVersion         OperationKind = "publish_version"
	OperationKindRollbackBank           OperationKind = "rollback_bank"
	OperationKindSubmitPracticeAnswer   OperationKind = "submit_practice_answer"
	OperationKindUnfavoriteQuestion     OperationKind = "unfavorite_question"
	OperationKindUnpublishVersion       OperationKind = "unpublish_version"
	OperationKindValidateVersion        OperationKind = "validate_version"
)

// Valid indicates whether the value is a known member of the OperationKind enum.
func (e OperationKind) Valid() bool {
	switch e {
	case OperationKindCreateBankVersion:
		return true
	case OperationKindCreateFavoritesSession:
		return true
	case OperationKindCreateFeedback:
		return true
	case OperationKindCreatePracticeSession:
		return true
	case OperationKindCreateWorkshopBank:
		return true
	case OperationKindFavoriteQuestion:
		return true
	case OperationKindImportBank:
		return true
	case OperationKindPublishVersion:
		return true
	case OperationKindRollbackBank:
		return true
	case OperationKindSubmitPracticeAnswer:
		return true
	case OperationKindUnfavoriteQuestion:
		return true
	case OperationKindUnpublishVersion:
		return true
	case OperationKindValidateVersion:
		return true
	default:
		return false
	}
}

// Defines values for PracticeSessionMode.
const (
	PracticeSessionModeChapter   PracticeSessionMode = "chapter"
	PracticeSessionModeDifficult PracticeSessionMode = "difficult"
	PracticeSessionModeFavorites PracticeSessionMode = "favorites"
	PracticeSessionModeRandom    PracticeSessionMode = "random"
)

// Valid indicates whether the value is a known member of the PracticeSessionMode enum.
func (e PracticeSessionMode) Valid() bool {
	switch e {
	case PracticeSessionModeChapter:
		return true
	case PracticeSessionModeDifficult:
		return true
	case PracticeSessionModeFavorites:
		return true
	case PracticeSessionModeRandom:
		return true
	default:
		return false
	}
}

// Defines values for QuestionFeedbackCategory.
const (
	QuestionFeedbackCategoryAmbiguous   QuestionFeedbackCategory = "ambiguous"
	QuestionFeedbackCategoryOther       QuestionFeedbackCategory = "other"
	QuestionFeedbackCategoryOutdated    QuestionFeedbackCategory = "outdated"
	QuestionFeedbackCategoryTypo        QuestionFeedbackCategory = "typo"
	QuestionFeedbackCategoryWrongAnswer QuestionFeedbackCategory = "wrong_answer"
)

// Valid indicates whether the value is a known member of the QuestionFeedbackCategory enum.
func (e QuestionFeedbackCategory) Valid() bool {
	switch e {
	case QuestionFeedbackCategoryAmbiguous:
		return true
	case QuestionFeedbackCategoryOther:
		return true
	case QuestionFeedbackCategoryOutdated:
		return true
	case QuestionFeedbackCategoryTypo:
		return true
	case QuestionFeedbackCategoryWrongAnswer:
		return true
	default:
		return false
	}
}

// Defines values for QuestionType.
const (
	QuestionTypeBlank  QuestionType = "blank"
	QuestionTypeJudge  QuestionType = "judge"
	QuestionTypeMulti  QuestionType = "multi"
	QuestionTypeSingle QuestionType = "single"
)

// Valid indicates whether the value is a known member of the QuestionType enum.
func (e QuestionType) Valid() bool {
	switch e {
	case QuestionTypeBlank:
		return true
	case QuestionTypeJudge:
		return true
	case QuestionTypeMulti:
		return true
	case QuestionTypeSingle:
		return true
	default:
		return false
	}
}

// Defines values for RandomPracticeSelectionMode.
const (
	RandomPracticeSelectionModeRandom RandomPracticeSelectionMode = "random"
)

// Valid indicates whether the value is a known member of the RandomPracticeSelectionMode enum.
func (e RandomPracticeSelectionMode) Valid() bool {
	switch e {
	case RandomPracticeSelectionModeRandom:
		return true
	default:
		return false
	}
}

// Defines values for RankingPageMetric.
const (
	CorrectAnswerCount RankingPageMetric = "correct_answer_count"
)

// Valid indicates whether the value is a known member of the RankingPageMetric enum.
func (e RankingPageMetric) Valid() bool {
	switch e {
	case CorrectAnswerCount:
		return true
	default:
		return false
	}
}

// Defines values for RankingPageScope.
const (
	Bank    RankingPageScope = "bank"
	Overall RankingPageScope = "overall"
)

// Valid indicates whether the value is a known member of the RankingPageScope enum.
func (e RankingPageScope) Valid() bool {
	switch e {
	case Bank:
		return true
	case Overall:
		return true
	default:
		return false
	}
}

// Defines values for RankingPeriod.
const (
	RankingPeriodLifetime RankingPeriod = "lifetime"
	RankingPeriodWeekly   RankingPeriod = "weekly"
)

// Valid indicates whether the value is a known member of the RankingPeriod enum.
func (e RankingPeriod) Valid() bool {
	switch e {
	case RankingPeriodLifetime:
		return true
	case RankingPeriodWeekly:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessEnvelopeDataStatus.
const (
	ReadinessEnvelopeDataStatusOk ReadinessEnvelopeDataStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessEnvelopeDataStatus enum.
func (e ReadinessEnvelopeDataStatus) Valid() bool {
	switch e {
	case ReadinessEnvelopeDataStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for WorkshopBankVersionState.
const (
	WorkshopBankVersionStateDraft     WorkshopBankVersionState = "draft"
	WorkshopBankVersionStateLegacy    WorkshopBankVersionState = "legacy"
	WorkshopBankVersionStateValidated WorkshopBankVersionState = "validated"
)

// Valid indicates whether the value is a known member of the WorkshopBankVersionState enum.
func (e WorkshopBankVersionState) Valid() bool {
	switch e {
	case WorkshopBankVersionStateDraft:
		return true
	case WorkshopBankVersionStateLegacy:
		return true
	case WorkshopBankVersionStateValidated:
		return true
	default:
		return false
	}
}

// Defines values for WorkshopFeedbackCategory.
const (
	WorkshopFeedbackCategoryAmbiguous   WorkshopFeedbackCategory = "ambiguous"
	WorkshopFeedbackCategoryOther       WorkshopFeedbackCategory = "other"
	WorkshopFeedbackCategoryOutdated    WorkshopFeedbackCategory = "outdated"
	WorkshopFeedbackCategoryTypo        WorkshopFeedbackCategory = "typo"
	WorkshopFeedbackCategoryWrongAnswer WorkshopFeedbackCategory = "wrong_answer"
)

// Valid indicates whether the value is a known member of the WorkshopFeedbackCategory enum.
func (e WorkshopFeedbackCategory) Valid() bool {
	switch e {
	case WorkshopFeedbackCategoryAmbiguous:
		return true
	case WorkshopFeedbackCategoryOther:
		return true
	case WorkshopFeedbackCategoryOutdated:
		return true
	case WorkshopFeedbackCategoryTypo:
		return true
	case WorkshopFeedbackCategoryWrongAnswer:
		return true
	default:
		return false
	}
}

// Defines values for WorkshopVersionDetailState.
const (
	WorkshopVersionDetailStateDraft     WorkshopVersionDetailState = "draft"
	WorkshopVersionDetailStateValidated WorkshopVersionDetailState = "validated"
)

// Valid indicates whether the value is a known member of the WorkshopVersionDetailState enum.
func (e WorkshopVersionDetailState) Valid() bool {
	switch e {
	case WorkshopVersionDetailStateDraft:
		return true
	case WorkshopVersionDetailStateValidated:
		return true
	default:
		return false
	}
}

// Defines values for RankingPeriodParam.
const (
	RankingPeriodParamLifetime RankingPeriodParam = "lifetime"
	RankingPeriodParamWeekly   RankingPeriodParam = "weekly"
)

// Valid indicates whether the value is a known member of the RankingPeriodParam enum.
func (e RankingPeriodParam) Valid() bool {
	switch e {
	case RankingPeriodParamLifetime:
		return true
	case RankingPeriodParamWeekly:
		return true
	default:
		return false
	}
}

// Defines values for GetBankRankingParamsPeriod.
const (
	GetBankRankingParamsPeriodLifetime GetBankRankingParamsPeriod = "lifetime"
	GetBankRankingParamsPeriodWeekly   GetBankRankingParamsPeriod = "weekly"
)

// Valid indicates whether the value is a known member of the GetBankRankingParamsPeriod enum.
func (e GetBankRankingParamsPeriod) Valid() bool {
	switch e {
	case GetBankRankingParamsPeriodLifetime:
		return true
	case GetBankRankingParamsPeriodWeekly:
		return true
	default:
		return false
	}
}

// Defines values for GetOverallRankingParamsPeriod.
const (
	GetOverallRankingParamsPeriodLifetime GetOverallRankingParamsPeriod = "lifetime"
	GetOverallRankingParamsPeriodWeekly   GetOverallRankingParamsPeriod = "weekly"
)

// Valid indicates whether the value is a known member of the GetOverallRankingParamsPeriod enum.
func (e GetOverallRankingParamsPeriod) Valid() bool {
	switch e {
	case GetOverallRankingParamsPeriodLifetime:
		return true
	case GetOverallRankingParamsPeriodWeekly:
		return true
	default:
		return false
	}
}

// AnswerResult defines model for AnswerResult.
type AnswerResult struct {
	Analysis          *string            `json:"analysis,omitempty"`
	Correct           bool               `json:"correct"`
	ExpectedAnswer    interface{}        `json:"expected_answer,omitempty"`
	QuestionId        openapi_types.UUID `json:"question_id"`
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
	Replayed          bool               `json:"replayed"`
}

// AnswerResultEnvelope defines model for AnswerResultEnvelope.
type AnswerResultEnvelope struct {
	Data      AnswerResult `json:"data"`
	RequestId RequestID    `json:"request_id"`
}

// AnswerSubmission defines model for AnswerSubmission.
type AnswerSubmission struct {
	Answer            interface{}        `json:"answer"`
	QuestionId        openapi_types.UUID `json:"question_id"`
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
}

// BankImportRequest defines model for BankImportRequest.
type BankImportRequest struct {
	// ExpectedVersion Workshop clients send the observed lifecycle version. Omission is retained for older import clients and serializes against the current version while still creating only an unpublished draft.
	ExpectedVersion *int                    `json:"expected_version,omitempty"`
	Questions       []ImportedQuestionInput `json:"questions"`
	SourceSha256    string                  `json:"source_sha256"`
}

// BankListEnvelope defines model for BankListEnvelope.
type BankListEnvelope struct {
	Data      []BankVersion `json:"data"`
	RequestId RequestID     `json:"request_id"`
}

// BankVersion defines model for BankVersion.
type BankVersion struct {
	// BankId Stable across every version of this bank.
	BankId  openapi_types.UUID `json:"bank_id"`
	BankKey string             `json:"bank_key"`

	// BankVersionId Immutable identifier for exact bank content.
	BankVersionId openapi_types.UUID `json:"bank_version_id"`
	Chapters      []Chapter          `json:"chapters"`
	ContentSha256 string             `json:"content_sha256"`
	Name          string             `json:"name"`
	QuestionCount int                `json:"question_count"`
}

// Chapter defines model for Chapter.
type Chapter struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// ChapterPracticeSelection defines model for ChapterPracticeSelection.
type ChapterPracticeSelection struct {
	BankId        openapi_types.UUID           `json:"bank_id"`
	BankVersionId openapi_types.UUID           `json:"bank_version_id"`
	ChapterId     string                       `json:"chapter_id"`
	Mode          ChapterPracticeSelectionMode `json:"mode"`
	QuestionCount *int                         `json:"question_count,omitempty"`
}

// ChapterPracticeSelectionMode defines model for ChapterPracticeSelection.Mode.
type ChapterPracticeSelectionMode string

// ChoicePracticeQuestion defines model for ChoicePracticeQuestion.
type ChoicePracticeQuestion struct {
	Chapter           string                     `json:"chapter"`
	ChapterId         string                     `json:"chapter_id"`
	Content           string                     `json:"content"`
	Options           []string                   `json:"options"`
	QuestionId        openapi_types.UUID         `json:"question_id"`
	QuestionVersionId openapi_types.UUID         `json:"question_version_id"`
	Type              ChoicePracticeQuestionType `json:"type"`
}

// ChoicePracticeQuestionType defines model for ChoicePracticeQuestion.Type.
type ChoicePracticeQuestionType string

// ConsoleSummaryEnvelope defines model for ConsoleSummaryEnvelope.
type ConsoleSummaryEnvelope struct {
	Data struct {
		AsOf    time.Time                    `json:"as_of"`
		Id      ConsoleSummaryEnvelopeDataId `json:"id"`
		Metrics []struct {
			Hint  *string `json:"hint,omitempty"`
			Label string  `json:"label"`
			Value string  `json:"value"`
		} `json:"metrics"`
		Status        ConsoleSummaryEnvelopeDataStatus `json:"status"`
		StatusMessage string                           `json:"status_message"`
	} `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// ConsoleSummaryEnvelopeDataId defines model for ConsoleSummaryEnvelope.Data.Id.
type ConsoleSummaryEnvelopeDataId string

// ConsoleSummaryEnvelopeDataStatus defines model for ConsoleSummaryEnvelope.Data.Status.
type ConsoleSummaryEnvelopeDataStatus string

// CreateBankVersion defines model for CreateBankVersion.
type CreateBankVersion struct {
	ExpectedVersion int                     `json:"expected_version"`
	Questions       []ImportedQuestionInput `json:"questions"`
}

// CreatePracticeSession defines model for CreatePracticeSession.
type CreatePracticeSession struct {
	union json.RawMessage
}

// CreateWorkshopBank defines model for CreateWorkshopBank.
type CreateWorkshopBank struct {
	BankKey string `json:"bank_key"`
	Name    string `json:"name"`
}

// CutoverEvidenceEnvelope defines model for CutoverEvidenceEnvelope.
type CutoverEvidenceEnvelope struct {
	Data struct {
		Database        CutoverEvidenceEnvelopeDataDatabase `json:"database"`
		MigrationCursor int64                               `json:"migration_cursor"`
		MigrationRunId  openapi_types.UUID                  `json:"migration_run_id"`
		ReleaseSha      string                              `json:"release_sha"`
		WritesEnabled   bool                                `json:"writes_enabled"`
	} `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// CutoverEvidenceEnvelopeDataDatabase defines model for CutoverEvidenceEnvelope.Data.Database.
type CutoverEvidenceEnvelopeDataDatabase string

// DifficultPracticeSelection defines model for DifficultPracticeSelection.
type DifficultPracticeSelection struct {
	BankId        openapi_types.UUID             `json:"bank_id"`
	BankVersionId openapi_types.UUID             `json:"bank_version_id"`
	Mode          DifficultPracticeSelectionMode `json:"mode"`
	QuestionCount *int                           `json:"question_count,omitempty"`
}

// DifficultPracticeSelectionMode defines model for DifficultPracticeSelection.Mode.
type DifficultPracticeSelectionMode string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error     Error     `json:"error"`
	RequestId RequestID `json:"request_id"`
}

// FavoriteFolder defines model for FavoriteFolder.
type FavoriteFolder struct {
	AvailableCount   int                `json:"available_count"`
	BankId           openapi_types.UUID `json:"bank_id"`
	BankName         string             `json:"bank_name"`
	UnavailableCount int                `json:"unavailable_count"`
}

// FavoriteListEnvelope defines model for FavoriteListEnvelope.
type FavoriteListEnvelope struct {
	Data      []FavoriteQuestion `json:"data"`
	RequestId RequestID          `json:"request_id"`
}

// FavoriteQuestion defines model for FavoriteQuestion.
type FavoriteQuestion struct {
	Available  bool               `json:"available"`
	BankId     openapi_types.UUID `json:"bank_id"`
	QuestionId openapi_types.UUID `json:"question_id"`

	// QuestionVersionId Present only when available.
	QuestionVersionId *openapi_types.UUID `json:"question_version_id,omitempty"`
}

// FavoritesOverviewEnvelope defines model for FavoritesOverviewEnvelope.
type FavoritesOverviewEnvelope struct {
	Data      []FavoriteFolder `json:"data"`
	RequestId RequestID        `json:"request_id"`
}

// FeedbackStatus defines model for FeedbackStatus.
type FeedbackStatus struct {
	BankId            openapi_types.UUID     `json:"bank_id"`
	Category          FeedbackStatusCategory `json:"category"`
	CreatedAt         time.Time              `json:"created_at"`
	FeedbackId        openapi_types.UUID     `json:"feedback_id"`
	QuestionId        openapi_types.UUID     `json:"question_id"`
	QuestionVersionId openapi_types.UUID     `json:"question_version_id"`
	Status            FeedbackStatusStatus   `json:"status"`
	UpdatedAt         time.Time              `json:"updated_at"`
}

// FeedbackStatusCategory defines model for FeedbackStatus.Category.
type FeedbackStatusCategory string

// FeedbackStatusStatus defines model for FeedbackStatus.Status.
type FeedbackStatusStatus string

// FeedbackStatusEnvelope defines model for FeedbackStatusEnvelope.
type FeedbackStatusEnvelope struct {
	Data      FeedbackStatus `json:"data"`
	RequestId RequestID      `json:"request_id"`
}

// FeedbackStatusListEnvelope defines model for FeedbackStatusListEnvelope.
type FeedbackStatusListEnvelope struct {
	Data struct {
		Items []FeedbackStatus `json:"items"`
	} `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// HealthEnvelope defines model for HealthEnvelope.
type HealthEnvelope struct {
	Data struct {
		Status HealthEnvelopeDataStatus `json:"status"`
	} `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// HealthEnvelopeDataStatus defines model for HealthEnvelope.Data.Status.
type HealthEnvelopeDataStatus string

// ImportReport defines model for ImportReport.
type ImportReport struct {
	Accepted      bool                `json:"accepted"`
	AnsweredCount int                 `json:"answered_count"`
	BankId        *openapi_types.UUID `json:"bank_id,omitempty"`
	BankVersionId *openapi_types.UUID `json:"bank_version_id,omitempty"`
	ChapterCounts map[string]int      `json:"chapter_counts"`
	ContentSha256 *string             `json:"content_sha256,omitempty"`
	Errors        []struct {
		Code    string `json:"code"`
		Message string `json:"message"`
		Path    string `json:"path"`
	} `json:"errors"`
	QuestionCount   int                      `json:"question_count"`
	Questions       []ImportedQuestionReport `json:"questions"`
	SourceSha256    string                   `json:"source_sha256"`
	TypeCounts      map[string]int           `json:"type_counts"`
	UnansweredCount int                      `json:"unanswered_count"`
}

// ImportReportEnvelope defines model for ImportReportEnvelope.
type ImportReportEnvelope struct {
	Data      ImportReport `json:"data"`
	RequestId RequestID    `json:"request_id"`
}

// ImportedQuestionInput defines model for ImportedQuestionInput.
type ImportedQuestionInput struct {
	Analysis         *string      `json:"analysis,omitempty"`
	Answer           interface{}  `json:"answer"`
	Chapter          *string      `json:"chapter,omitempty"`
	ChapterId        string       `json:"chapter_id"`
	Content          string       `json:"content"`
	Options          *[]string    `json:"options,omitempty"`
	SourceQuestionId string       `json:"source_question_id"`
	Type             QuestionType `json:"type"`
}

// ImportedQuestionReport defines model for ImportedQuestionReport.
type ImportedQuestionReport struct {
	AnswerSha256  string `json:"answer_sha256"`
	ContentSha256 string `json:"content_sha256"`

	// QuestionId Stable identity independent of edits.
	QuestionId openapi_types.UUID `json:"question_id"`

	// QuestionVersionId Immutable content identity.
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
	SourceQuestionId  string             `json:"source_question_id"`
}

// LearningReport defines model for LearningReport.
type LearningReport struct {
	BankId           openapi_types.UUID        `json:"bank_id"`
	ContentVersionId openapi_types.UUID        `json:"content_version_id"`
	CreatedAt        time.Time                 `json:"created_at"`
	Evidence         []LearningReportEvidence  `json:"evidence"`
	EvidenceUntil    time.Time                 `json:"evidence_until"`
	Findings         []LearningReportFinding   `json:"findings"`
	Goal             LearningReportGoal        `json:"goal"`
	NextStep         LearningReportAction      `json:"next_step"`
	ReportId         openapi_types.UUID        `json:"report_id"`
	Statistics       []LearningReportStatistic `json:"statistics"`
	Status           LearningReportStatus      `json:"status"`
}

// LearningReportGoal defines model for LearningReport.Goal.
type LearningReportGoal string

// LearningReportStatus defines model for LearningReport.Status.
type LearningReportStatus string

// LearningReportAction defines model for LearningReportAction.
type LearningReportAction struct {
	Kind        LearningReportActionKind `json:"kind"`
	Lesson      *LearningReportLesson    `json:"lesson,omitempty"`
	QuestionIds *[]openapi_types.UUID    `json:"question_ids,omitempty"`
	Reason      string                   `json:"reason"`
	TagId       *string                  `json:"tag_id,omitempty"`
}

// LearningReportActionKind defines model for LearningReportAction.Kind.
type LearningReportActionKind string

// LearningReportClearResult defines model for LearningReportClearResult.
type LearningReportClearResult struct {
	Cleared  bool  `json:"cleared"`
	Revision int64 `json:"revision"`
}

// LearningReportClearResultEnvelope defines model for LearningReportClearResultEnvelope.
type LearningReportClearResultEnvelope struct {
	Data      LearningReportClearResult `json:"data"`
	RequestId string                    `json:"request_id"`
}

// LearningReportEnvelope defines model for LearningReportEnvelope.
type LearningReportEnvelope struct {
	Data      LearningReport `json:"data"`
	RequestId string         `json:"request_id"`
}

// LearningReportEvidence defines model for LearningReportEvidence.
type LearningReportEvidence struct {
	Correct           bool               `json:"correct"`
	EvidenceId        string             `json:"evidence_id"`
	ExpectedAnswer    interface{}        `json:"expected_answer"`
	Question          string             `json:"question"`
	QuestionId        openapi_types.UUID `json:"question_id"`
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
	SubmittedAnswer   interface{}        `json:"submitted_answer"`
	SubmittedAt       time.Time          `json:"submitted_at"`
}

// LearningReportFinding defines model for LearningReportFinding.
type LearningReportFinding struct {
	EvidenceIds    []string                    `json:"evidence_ids"`
	Observation    string                      `json:"observation"`
	PossibleReason *string                     `json:"possible_reason,omitempty"`
	Status         LearningReportFindingStatus `json:"status"`
	TagId          string                      `json:"tag_id"`
}

// LearningReportFindingStatus defines model for LearningReportFinding.Status.
type LearningReportFindingStatus string

// LearningReportLesson defines model for LearningReportLesson.
type LearningReportLesson struct {
	Body     string                 `json:"body"`
	LessonId string                 `json:"lesson_id"`
	Sources  []LearningReportSource `json:"sources"`
	Title    string                 `json:"title"`
}

// LearningReportPreferences defines model for LearningReportPreferences.
type LearningReportPreferences struct {
	BankId                  openapi_types.UUID            `json:"bank_id"`
	ChapterIds              []string                      `json:"chapter_ids"`
	Enabled                 bool                          `json:"enabled"`
	ExternalAnalysisConsent bool                          `json:"external_analysis_consent"`
	Goal                    LearningReportPreferencesGoal `json:"goal"`
	IntervalDays            int                           `json:"interval_days"`
	NextDueAt               *time.Time                    `json:"next_due_at,omitempty"`
	Revision                int64                         `json:"revision"`
	UpdatedAt               *time.Time                    `json:"updated_at,omitempty"`
}

// LearningReportPreferencesGoal defines model for LearningReportPreferences.Goal.
type LearningReportPreferencesGoal string

// LearningReportPreferencesEnvelope defines model for LearningReportPreferencesEnvelope.
type LearningReportPreferencesEnvelope struct {
	Data      LearningReportPreferences `json:"data"`
	RequestId string                    `json:"request_id"`
}

// LearningReportPreferencesUpdate defines model for LearningReportPreferencesUpdate.
type LearningReportPreferencesUpdate struct {
	ChapterIds              []string                            `json:"chapter_ids"`
	Enabled                 bool                                `json:"enabled"`
	ExternalAnalysisConsent bool                                `json:"external_analysis_consent"`
	Goal                    LearningReportPreferencesUpdateGoal `json:"goal"`
	IntervalDays            int                                 `json:"interval_days"`
}

// LearningReportPreferencesUpdateGoal defines model for LearningReportPreferencesUpdate.Goal.
type LearningReportPreferencesUpdateGoal string

// LearningReportSource defines model for LearningReportSource.
type LearningReportSource struct {
	Locator  string `json:"locator"`
	SourceId string `json:"source_id"`
	Title    string `json:"title"`
	Version  string `json:"version"`
}

// LearningReportStatistic defines model for LearningReportStatistic.
type LearningReportStatistic struct {
	AttemptCount        int64                          `json:"attempt_count"`
	FirstCorrectCount   int64                          `json:"first_correct_count"`
	Label               string                         `json:"label"`
	LatestCorrectCount  int64                          `json:"latest_correct_count"`
	RepeatAttemptCount  int64                          `json:"repeat_attempt_count"`
	RepeatCorrectCount  int64                          `json:"repeat_correct_count"`
	TagId               string                         `json:"tag_id"`
	TagKind             LearningReportStatisticTagKind `json:"tag_kind"`
	UniqueQuestionCount int64                          `json:"unique_question_count"`
}

// LearningReportStatisticTagKind defines model for LearningReportStatistic.TagKind.
type LearningReportStatisticTagKind string

// LearningReportTask defines model for LearningReportTask.
type LearningReportTask struct {
	BankId            openapi_types.UUID       `json:"bank_id"`
	CreatedAt         time.Time                `json:"created_at"`
	ReasonCode        *string                  `json:"reason_code,omitempty"`
	ReportId          *openapi_types.UUID      `json:"report_id,omitempty"`
	RetryAfterSeconds *int                     `json:"retry_after_seconds,omitempty"`
	Status            LearningReportTaskStatus `json:"status"`
	TaskId            openapi_types.UUID       `json:"task_id"`
}

// LearningReportTaskStatus defines model for LearningReportTask.Status.
type LearningReportTaskStatus string

// LearningReportTaskEnvelope defines model for LearningReportTaskEnvelope.
type LearningReportTaskEnvelope struct {
	Data      LearningReportTask `json:"data"`
	RequestId string             `json:"request_id"`
}

// LearningStateEnvelope defines model for LearningStateEnvelope.
type LearningStateEnvelope struct {
	Data      []LearningStateItem `json:"data"`
	RequestId RequestID           `json:"request_id"`
}

// LearningStateItem defines model for LearningStateItem.
type LearningStateItem struct {
	AttemptCount      int64              `json:"attempt_count"`
	BankId            openapi_types.UUID `json:"bank_id"`
	CorrectCount      int64              `json:"correct_count"`
	QuestionId        openapi_types.UUID `json:"question_id"`
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
	UpdatedAt         time.Time          `json:"updated_at"`
	Wrong             bool               `json:"wrong"`
}

// LegacyRankingEnvelope defines model for LegacyRankingEnvelope.
type LegacyRankingEnvelope struct {
	Data      LegacyRankingPage `json:"data"`
	RequestId RequestID         `json:"request_id"`
}

// LegacyRankingPage defines model for LegacyRankingPage.
type LegacyRankingPage struct {
	CapturedAt    *time.Time `json:"captured_at"`
	ContentSha256 string     `json:"content_sha256"`
	Entries       []struct {
		Correct int    `json:"correct"`
		Name    string `json:"name"`
		Rank    int    `json:"rank"`
		Total   int    `json:"total"`
	} `json:"entries"`
}

// MasterySubject defines model for MasterySubject.
type MasterySubject struct {
	BankId openapi_types.UUID `json:"bank_id"`

	// CorrectQuestions Active stable questions answered correctly at least once by this user.
	CorrectQuestions int64  `json:"correct_questions"`
	Label            string `json:"label"`

	// TotalQuestions Current active stable questions in this bank.
	TotalQuestions int64 `json:"total_questions"`

	// Value Correct stable questions divided by the active bank question count.
	Value int `json:"value"`
}

// NonChoicePracticeQuestion defines model for NonChoicePracticeQuestion.
type NonChoicePracticeQuestion struct {
	Chapter           string                        `json:"chapter"`
	ChapterId         string                        `json:"chapter_id"`
	Content           string                        `json:"content"`
	QuestionId        openapi_types.UUID            `json:"question_id"`
	QuestionVersionId openapi_types.UUID            `json:"question_version_id"`
	Type              NonChoicePracticeQuestionType `json:"type"`
}

// NonChoicePracticeQuestionType defines model for NonChoicePracticeQuestion.Type.
type NonChoicePracticeQuestionType string

// Operation defines model for Operation.
type Operation struct {
	IdempotencyKey string              `json:"idempotency_key"`
	OperationId    openapi_types.UUID  `json:"operation_id"`
	RequestId      RequestID           `json:"request_id"`
	ResourceId     *openapi_types.UUID `json:"resource_id,omitempty"`
	State          OperationState      `json:"state"`
}

// OperationState defines model for Operation.State.
type OperationState string

// OperationEnvelope defines model for OperationEnvelope.
type OperationEnvelope struct {
	Data      Operation `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// OperationKind defines model for OperationKind.
type OperationKind string

// PersonalPracticeStats defines model for PersonalPracticeStats.
type PersonalPracticeStats struct {
	// Accuracy Rounded correct_answers divided by total_answers.
	Accuracy int `json:"accuracy"`

	// CorrectAnswers Correct immutable scored attempts owned by this user.
	CorrectAnswers int64            `json:"correct_answers"`
	Mastery        []MasterySubject `json:"mastery"`

	// StreakDays Consecutive Asia/Shanghai calendar days ending today or yesterday with at least one scored attempt.
	StreakDays int `json:"streak_days"`

	// TotalAnswers Count of immutable scored attempts owned by this user.
	TotalAnswers int64 `json:"total_answers"`
}

// PersonalPracticeStatsEnvelope defines model for PersonalPracticeStatsEnvelope.
type PersonalPracticeStatsEnvelope struct {
	Data      PersonalPracticeStats `json:"data"`
	RequestId RequestID             `json:"request_id"`
}

// PracticeQuestion defines model for PracticeQuestion.
type PracticeQuestion struct {
	union json.RawMessage
}

// PracticeSession defines model for PracticeSession.
type PracticeSession struct {
	BankId                   openapi_types.UUID  `json:"bank_id"`
	BankVersionId            openapi_types.UUID  `json:"bank_version_id"`
	ExcludedUnavailableCount int                 `json:"excluded_unavailable_count"`
	Mode                     PracticeSessionMode `json:"mode"`
	Questions                []PracticeQuestion  `json:"questions"`
	SessionId                openapi_types.UUID  `json:"session_id"`
}

// PracticeSessionEnvelope defines model for PracticeSessionEnvelope.
type PracticeSessionEnvelope struct {
	Data      PracticeSession `json:"data"`
	RequestId RequestID       `json:"request_id"`
}

// PracticeSessionMode defines model for PracticeSessionMode.
type PracticeSessionMode string

// QuestionFeedback defines model for QuestionFeedback.
type QuestionFeedback struct {
	BankId            openapi_types.UUID       `json:"bank_id"`
	Category          QuestionFeedbackCategory `json:"category"`
	Detail            string                   `json:"detail"`
	QuestionId        openapi_types.UUID       `json:"question_id"`
	QuestionVersionId openapi_types.UUID       `json:"question_version_id"`
}

// QuestionFeedbackCategory defines model for QuestionFeedback.Category.
type QuestionFeedbackCategory string

// QuestionReference defines model for QuestionReference.
type QuestionReference struct {
	// QuestionId Stable identity independent of edits.
	QuestionId openapi_types.UUID `json:"question_id"`

	// QuestionVersionId Immutable content identity.
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
}

// QuestionType defines model for QuestionType.
type QuestionType string

// RandomPracticeSelection defines model for RandomPracticeSelection.
type RandomPracticeSelection struct {
	BankId        openapi_types.UUID          `json:"bank_id"`
	BankVersionId openapi_types.UUID          `json:"bank_version_id"`
	Mode          RandomPracticeSelectionMode `json:"mode"`
	QuestionCount *int                        `json:"question_count,omitempty"`
}

// RandomPracticeSelectionMode defines model for RandomPracticeSelection.Mode.
type RandomPracticeSelectionMode string

// RankingEnvelope defines model for RankingEnvelope.
type RankingEnvelope struct {
	Data      RankingPage `json:"data"`
	RequestId RequestID   `json:"request_id"`
}

// RankingPage defines model for RankingPage.
type RankingPage struct {
	BankId  *openapi_types.UUID `json:"bank_id,omitempty"`
	Entries []struct {
		CorrectAnswerCount int `json:"correct_answer_count"`

		// GuestKey Internal-only stable anonymous identity key (the session's immutable actor_key text) for guest learners; null for signed-in learners. Portal Gateway uses it only to derive a stable 游客x display label and MUST never expose it before any external response (ADR-0038).
		GuestKey *string `json:"guest_key,omitempty"`
		Rank     int     `json:"rank"`

		// UserId Internal-only stable actor key; null for guest learners. Portal Gateway MUST strip this field before any external response (ADR-0036 privacy contract).
		UserId *openapi_types.UUID `json:"user_id"`
	} `json:"entries"`
	Metric RankingPageMetric `json:"metric"`
	Period RankingPeriod     `json:"period"`
	Scope  RankingPageScope  `json:"scope"`
}

// RankingPageMetric defines model for RankingPage.Metric.
type RankingPageMetric string

// RankingPageScope defines model for RankingPage.Scope.
type RankingPageScope string

// RankingPeriod defines model for RankingPeriod.
type RankingPeriod string

// ReadinessEnvelope defines model for ReadinessEnvelope.
type ReadinessEnvelope struct {
	Data struct {
		Status ReadinessEnvelopeDataStatus `json:"status"`
	} `json:"data"`
	RequestId RequestID `json:"request_id"`
}

// ReadinessEnvelopeDataStatus defines model for ReadinessEnvelope.Data.Status.
type ReadinessEnvelopeDataStatus string

// RequestID defines model for RequestID.
type RequestID = string

// RollbackCommand defines model for RollbackCommand.
type RollbackCommand struct {
	ExpectedVersion     int                `json:"expected_version"`
	Note                *string            `json:"note,omitempty"`
	TargetBankVersionId openapi_types.UUID `json:"target_bank_version_id"`
}

// VersionCommand defines model for VersionCommand.
type VersionCommand struct {
	ExpectedVersion int     `json:"expected_version"`
	Note            *string `json:"note,omitempty"`
}

// WorkshopBank defines model for WorkshopBank.
type WorkshopBank struct {
	ActiveVersionId  *openapi_types.UUID   `json:"active_version_id,omitempty"`
	BankId           openapi_types.UUID    `json:"bank_id"`
	BankKey          string                `json:"bank_key"`
	LifecycleVersion int64                 `json:"lifecycle_version"`
	Name             string                `json:"name"`
	Versions         []WorkshopBankVersion `json:"versions"`
}

// WorkshopBankListEnvelope defines model for WorkshopBankListEnvelope.
type WorkshopBankListEnvelope struct {
	Data      []WorkshopBank `json:"data"`
	RequestId RequestID      `json:"request_id"`
}

// WorkshopBankVersion defines model for WorkshopBankVersion.
type WorkshopBankVersion struct {
	Active        bool                     `json:"active"`
	BankVersionId openapi_types.UUID       `json:"bank_version_id"`
	ContentSha256 string                   `json:"content_sha256"`
	QuestionCount int                      `json:"question_count"`
	State         WorkshopBankVersionState `json:"state"`
	ValidatedAt   *time.Time               `json:"validated_at,omitempty"`
}

// WorkshopBankVersionState defines model for WorkshopBankVersion.State.
type WorkshopBankVersionState string

// WorkshopFeedback defines model for WorkshopFeedback.
type WorkshopFeedback struct {
	BankId            openapi_types.UUID       `json:"bank_id"`
	Category          WorkshopFeedbackCategory `json:"category"`
	CreatedAt         time.Time                `json:"created_at"`
	Detail            string                   `json:"detail"`
	FeedbackId        openapi_types.UUID       `json:"feedback_id"`
	QuestionId        openapi_types.UUID       `json:"question_id"`
	QuestionVersionId openapi_types.UUID       `json:"question_version_id"`
}

// WorkshopFeedbackCategory defines model for WorkshopFeedback.Category.
type WorkshopFeedbackCategory string

// WorkshopFeedbackEnvelope defines model for WorkshopFeedbackEnvelope.
type WorkshopFeedbackEnvelope struct {
	Data      WorkshopFeedback `json:"data"`
	RequestId RequestID        `json:"request_id"`
}

// WorkshopQuestionDetail defines model for WorkshopQuestionDetail.
type WorkshopQuestionDetail struct {
	Analysis          *string            `json:"analysis,omitempty"`
	Answer            interface{}        `json:"answer"`
	Chapter           *string            `json:"chapter,omitempty"`
	ChapterId         string             `json:"chapter_id"`
	Content           string             `json:"content"`
	Options           *[]string          `json:"options,omitempty"`
	Position          int                `json:"position"`
	QuestionId        openapi_types.UUID `json:"question_id"`
	QuestionVersionId openapi_types.UUID `json:"question_version_id"`
	SourceQuestionId  string             `json:"source_question_id"`
	Type              QuestionType       `json:"type"`
}

// WorkshopVersionDetail defines model for WorkshopVersionDetail.
type WorkshopVersionDetail struct {
	BankId        openapi_types.UUID         `json:"bank_id"`
	BankVersionId openapi_types.UUID         `json:"bank_version_id"`
	ContentSha256 string                     `json:"content_sha256"`
	Questions     []WorkshopQuestionDetail   `json:"questions"`
	State         WorkshopVersionDetailState `json:"state"`
}

// WorkshopVersionDetailState defines model for WorkshopVersionDetail.State.
type WorkshopVersionDetailState string

// WorkshopVersionDetailEnvelope defines model for WorkshopVersionDetailEnvelope.
type WorkshopVersionDetailEnvelope struct {
	Data      WorkshopVersionDetail `json:"data"`
	RequestId RequestID             `json:"request_id"`
}

// BankID defines model for BankID.
type BankID = openapi_types.UUID

// BankVersionID defines model for BankVersionID.
type BankVersionID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OperationKindParam defines model for OperationKindParam.
type OperationKindParam = OperationKind

// QuestionID defines model for QuestionID.
type QuestionID = openapi_types.UUID

// RankingPeriodParam defines model for RankingPeriodParam.
type RankingPeriodParam string

// SessionID defines model for SessionID.
type SessionID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// ServiceReplay defines model for ServiceReplay.
type ServiceReplay = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// CreateFavoritesPracticeSessionParams defines parameters for CreateFavoritesPracticeSession.
type CreateFavoritesPracticeSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UnfavoriteQuestionParams defines parameters for UnfavoriteQuestion.
type UnfavoriteQuestionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// FavoriteQuestionParams defines parameters for FavoriteQuestion.
type FavoriteQuestionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetBankRankingParams defines parameters for GetBankRanking.
type GetBankRankingParams struct {
	Period *GetBankRankingParamsPeriod `form:"period,omitempty" json:"period,omitempty"`
}

// GetBankRankingParamsPeriod defines parameters for GetBankRanking.
type GetBankRankingParamsPeriod string

// GetQuizCraftCutoverEvidenceParams defines parameters for GetQuizCraftCutoverEvidence.
type GetQuizCraftCutoverEvidenceParams struct {
	RunId      openapi_types.UUID `form:"run_id" json:"run_id"`
	SourceHead int64              `form:"source_head" json:"source_head"`
}

// CreateQuestionFeedbackParams defines parameters for CreateQuestionFeedback.
type CreateQuestionFeedbackParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetQuizCraftOperationParams defines parameters for GetQuizCraftOperation.
type GetQuizCraftOperationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPortalFavoriteQuestionsParams defines parameters for ListPortalFavoriteQuestions.
type ListPortalFavoriteQuestionsParams struct {
	// XActorUserId UUID of the Portal Session subject; it is the sixth line of the HMAC canonical request.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// CreatePortalFavoritesSessionParams defines parameters for CreatePortalFavoritesSession.
type CreatePortalFavoritesSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UnfavoritePortalQuestionParams defines parameters for UnfavoritePortalQuestion.
type UnfavoritePortalQuestionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// FavoritePortalQuestionParams defines parameters for FavoritePortalQuestion.
type FavoritePortalQuestionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ClearPortalLearningReportsParams defines parameters for ClearPortalLearningReports.
type ClearPortalLearningReportsParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId   openapi_types.UUID `json:"X-Actor-User-Id"`
	IdempotencyKey IdempotencyKey     `json:"Idempotency-Key"`
}

// RequestPortalLearningReportParams defines parameters for RequestPortalLearningReport.
type RequestPortalLearningReportParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId   openapi_types.UUID `json:"X-Actor-User-Id"`
	IdempotencyKey IdempotencyKey     `json:"Idempotency-Key"`
}

// GetPortalLatestLearningReportParams defines parameters for GetPortalLatestLearningReport.
type GetPortalLatestLearningReportParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// GetPortalLearningReportPreferencesParams defines parameters for GetPortalLearningReportPreferences.
type GetPortalLearningReportPreferencesParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// UpdatePortalLearningReportPreferencesParams defines parameters for UpdatePortalLearningReportPreferences.
type UpdatePortalLearningReportPreferencesParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId   openapi_types.UUID `json:"X-Actor-User-Id"`
	IdempotencyKey IdempotencyKey     `json:"Idempotency-Key"`
}

// CreatePortalLearningReportPracticeSessionParams defines parameters for CreatePortalLearningReportPracticeSession.
type CreatePortalLearningReportPracticeSessionParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId   openapi_types.UUID `json:"X-Actor-User-Id"`
	IdempotencyKey IdempotencyKey     `json:"Idempotency-Key"`
}

// GetPortalLearningReportTaskParams defines parameters for GetPortalLearningReportTask.
type GetPortalLearningReportTaskParams struct {
	// XActorUserId Verified Portal actor, included in the service HMAC; never accepted from request JSON.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// GetPortalFavoritesOverviewParams defines parameters for GetPortalFavoritesOverview.
type GetPortalFavoritesOverviewParams struct {
	// XActorUserId UUID of the Portal Session subject; it is the sixth line of the HMAC canonical request.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// CreatePortalPracticeFeedbackParams defines parameters for CreatePortalPracticeFeedback.
type CreatePortalPracticeFeedbackParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetPortalPracticeFeedbackStatusParams defines parameters for GetPortalPracticeFeedbackStatus.
type GetPortalPracticeFeedbackStatusParams struct {
	// XActorUserId UUID of the Portal Session subject; it is the sixth line of the HMAC canonical request.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// CreatePortalPracticeSessionParams defines parameters for CreatePortalPracticeSession.
type CreatePortalPracticeSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SubmitPortalPracticeAnswerParams defines parameters for SubmitPortalPracticeAnswer.
type SubmitPortalPracticeAnswerParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePracticeSessionParams defines parameters for CreatePracticeSession.
type CreatePracticeSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// SubmitPracticeAnswerParams defines parameters for SubmitPracticeAnswer.
type SubmitPracticeAnswerParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetOverallRankingParams defines parameters for GetOverallRanking.
type GetOverallRankingParams struct {
	Period *GetOverallRankingParamsPeriod `form:"period,omitempty" json:"period,omitempty"`
}

// GetOverallRankingParamsPeriod defines parameters for GetOverallRanking.
type GetOverallRankingParamsPeriod string

// GetPersonalPracticeStatsParams defines parameters for GetPersonalPracticeStats.
type GetPersonalPracticeStatsParams struct {
	// XActorUserId UUID of the Portal Session subject; it is the sixth line of the HMAC canonical request.
	XActorUserId openapi_types.UUID `json:"X-Actor-User-Id"`
}

// CreateWorkshopBankParams defines parameters for CreateWorkshopBank.
type CreateWorkshopBankParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ImportWorkshopBankParams defines parameters for ImportWorkshopBank.
type ImportWorkshopBankParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RollbackWorkshopBankParams defines parameters for RollbackWorkshopBank.
type RollbackWorkshopBankParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateWorkshopBankVersionParams defines parameters for CreateWorkshopBankVersion.
type CreateWorkshopBankVersionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PublishWorkshopBankVersionParams defines parameters for PublishWorkshopBankVersion.
type PublishWorkshopBankVersionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UnpublishWorkshopBankVersionParams defines parameters for UnpublishWorkshopBankVersion.
type UnpublishWorkshopBankVersionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ValidateWorkshopBankVersionParams defines parameters for ValidateWorkshopBankVersion.
type ValidateWorkshopBankVersionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateQuestionFeedbackJSONRequestBody defines body for CreateQuestionFeedback for application/json ContentType.
type CreateQuestionFeedbackJSONRequestBody = QuestionFeedback

// UpdatePortalLearningReportPreferencesJSONRequestBody defines body for UpdatePortalLearningReportPreferences for application/json ContentType.
type UpdatePortalLearningReportPreferencesJSONRequestBody = LearningReportPreferencesUpdate

// CreatePortalPracticeFeedbackJSONRequestBody defines body for CreatePortalPracticeFeedback for application/json ContentType.
type CreatePortalPracticeFeedbackJSONRequestBody = QuestionFeedback

// CreatePortalPracticeSessionJSONRequestBody defines body for CreatePortalPracticeSession for application/json ContentType.
type CreatePortalPracticeSessionJSONRequestBody = CreatePracticeSession

// SubmitPortalPracticeAnswerJSONRequestBody defines body for SubmitPortalPracticeAnswer for application/json ContentType.
type SubmitPortalPracticeAnswerJSONRequestBody = AnswerSubmission

// CreatePracticeSessionJSONRequestBody defines body for CreatePracticeSession for application/json ContentType.
type CreatePracticeSessionJSONRequestBody = CreatePracticeSession

// SubmitPracticeAnswerJSONRequestBody defines body for SubmitPracticeAnswer for application/json ContentType.
type SubmitPracticeAnswerJSONRequestBody = AnswerSubmission

// CreateWorkshopBankJSONRequestBody defines body for CreateWorkshopBank for application/json ContentType.
type CreateWorkshopBankJSONRequestBody = CreateWorkshopBank

// ImportWorkshopBankJSONRequestBody defines body for ImportWorkshopBank for application/json ContentType.
type ImportWorkshopBankJSONRequestBody = BankImportRequest

// RollbackWorkshopBankJSONRequestBody defines body for RollbackWorkshopBank for application/json ContentType.
type RollbackWorkshopBankJSONRequestBody = RollbackCommand

// CreateWorkshopBankVersionJSONRequestBody defines body for CreateWorkshopBankVersion for application/json ContentType.
type CreateWorkshopBankVersionJSONRequestBody = CreateBankVersion

// PublishWorkshopBankVersionJSONRequestBody defines body for PublishWorkshopBankVersion for application/json ContentType.
type PublishWorkshopBankVersionJSONRequestBody = VersionCommand

// UnpublishWorkshopBankVersionJSONRequestBody defines body for UnpublishWorkshopBankVersion for application/json ContentType.
type UnpublishWorkshopBankVersionJSONRequestBody = VersionCommand

// ValidateWorkshopBankVersionJSONRequestBody defines body for ValidateWorkshopBankVersion for application/json ContentType.
type ValidateWorkshopBankVersionJSONRequestBody = VersionCommand

// AsRandomPracticeSelection returns the union data inside the CreatePracticeSession as a RandomPracticeSelection
func (t CreatePracticeSession) AsRandomPracticeSelection() (RandomPracticeSelection, error) {
	var body RandomPracticeSelection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRandomPracticeSelection overwrites any union data inside the CreatePracticeSession as the provided RandomPracticeSelection
func (t *CreatePracticeSession) FromRandomPracticeSelection(v RandomPracticeSelection) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRandomPracticeSelection performs a merge with any union data inside the CreatePracticeSession, using the provided RandomPracticeSelection
func (t *CreatePracticeSession) MergeRandomPracticeSelection(v RandomPracticeSelection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDifficultPracticeSelection returns the union data inside the CreatePracticeSession as a DifficultPracticeSelection
func (t CreatePracticeSession) AsDifficultPracticeSelection() (DifficultPracticeSelection, error) {
	var body DifficultPracticeSelection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDifficultPracticeSelection overwrites any union data inside the CreatePracticeSession as the provided DifficultPracticeSelection
func (t *CreatePracticeSession) FromDifficultPracticeSelection(v DifficultPracticeSelection) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDifficultPracticeSelection performs a merge with any union data inside the CreatePracticeSession, using the provided DifficultPracticeSelection
func (t *CreatePracticeSession) MergeDifficultPracticeSelection(v DifficultPracticeSelection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChapterPracticeSelection returns the union data inside the CreatePracticeSession as a ChapterPracticeSelection
func (t CreatePracticeSession) AsChapterPracticeSelection() (ChapterPracticeSelection, error) {
	var body ChapterPracticeSelection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChapterPracticeSelection overwrites any union data inside the CreatePracticeSession as the provided ChapterPracticeSelection
func (t *CreatePracticeSession) FromChapterPracticeSelection(v ChapterPracticeSelection) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChapterPracticeSelection performs a merge with any union data inside the CreatePracticeSession, using the provided ChapterPracticeSelection
func (t *CreatePracticeSession) MergeChapterPracticeSelection(v ChapterPracticeSelection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreatePracticeSession) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreatePracticeSession) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChoicePracticeQuestion returns the union data inside the PracticeQuestion as a ChoicePracticeQuestion
func (t PracticeQuestion) AsChoicePracticeQuestion() (ChoicePracticeQuestion, error) {
	var body ChoicePracticeQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoicePracticeQuestion overwrites any union data inside the PracticeQuestion as the provided ChoicePracticeQuestion
func (t *PracticeQuestion) FromChoicePracticeQuestion(v ChoicePracticeQuestion) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChoicePracticeQuestion performs a merge with any union data inside the PracticeQuestion, using the provided ChoicePracticeQuestion
func (t *PracticeQuestion) MergeChoicePracticeQuestion(v ChoicePracticeQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNonChoicePracticeQuestion returns the union data inside the PracticeQuestion as a NonChoicePracticeQuestion
func (t PracticeQuestion) AsNonChoicePracticeQuestion() (NonChoicePracticeQuestion, error) {
	var body NonChoicePracticeQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNonChoicePracticeQuestion overwrites any union data inside the PracticeQuestion as the provided NonChoicePracticeQuestion
func (t *PracticeQuestion) FromNonChoicePracticeQuestion(v NonChoicePracticeQuestion) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNonChoicePracticeQuestion performs a merge with any union data inside the PracticeQuestion, using the provided NonChoicePracticeQuestion
func (t *PracticeQuestion) MergeNonChoicePracticeQuestion(v NonChoicePracticeQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PracticeQuestion) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PracticeQuestion) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
